stages:
  - code_quality

run-linting:
  image: $CI_REGISTRY/docker-images/python-lint:latest
  stage: code_quality
  script:
    - python3 -m pip install -r env/requirements.txt
    - flake8 --ignore N803,N806,W503,E501 .
    - black --check . # Only check the files with black
    - pydocstyle --convention=numpy --add-ignore=D202 .

  only:
    - pushes
    - schedules
    - triggers
    - merge_requests

sonarqube-code-quality:
  image: registry.git.alteryx.com/alterml/code-free-ml-tools/sonarscanner:latest
  stage: code_quality
  tags:
    - linux-docker
  script:
    - cp sonarqube/sonar-scanner.properties /root/sonar-scanner/conf/sonar-scanner.properties
    - sonar-scanner -Dsonar.projectBaseDir=.
  only:
    - develop
    - merge_requests